name: Linux

on: [pull_request, push]

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ["5.30"]

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependency - JSON
        shell: bash
        run: cpan JSON
      - name: Install Dependency - Test::Pod
        shell: bash
        run: cpan Test::Pod
      - name: Install Dependency - Test::Pod::Coverage
        shell: bash
        run: cpan Test::Pod::Coverage
      - name: Install Dependency - Test::Spelling
        shell: bash
        run: cpan Test::Spelling
      - name: Install Dependency - Test::Version
        shell: bash
        run: cpan Test::Version
      - name: Install Dependency - ExtUtils::Config
        shell: bash
        run: cpan ExtUtils::Config
      - name: Install Dependency - ExtUtils::Helpers
        shell: bash
        run: cpan ExtUtils::Helpers
      - name: Install Dependency - ExtUtils::InstallPaths
        shell: bash
        run: cpan ExtUtils::InstallPaths
      - name: Install Dependency - Pod::Coverage::TrustPod
        shell: bash
        run: cpan Pod::Coverage::TrustPod
      - name: Install Dependency - Readonly
        shell: bash
        run: cpan Readonly
      - name: Install Dependency - Perl::Critic
        shell: bash
        run: cpan Perl::Critic
      - name: Install Dependency - Test::MinimumVersion
        shell: bash
        run: cpan Test::MinimumVersion
      - name: Install Dependency - Test::CPAN::Changes
        shell: bash
        run: cpan Test::CPAN::Changes
      - name: Install Dependency - Test::CPAN::Meta
        shell: bash
        run: cpan Test::CPAN::Meta
      - name: Install Dependency - Test::Mojibake
        shell: bash
        run: cpan Test::Mojibake
      - name: Install Dependency - Test::Portability::Files
        shell: bash
        run: cpan Test::Portability::Files
      - name: Install Dependency - URI
        shell: bash
        run: cpan URI
      - name: Install Dependency - boolean
        shell: bash
        run: cpan boolean
      - name: Install Dependency - List::MoreUtils
        shell: bash
        run: cpan List::MoreUtils
      - name: Install Dependency - Path::Tiny
        shell: bash
        run: cpan Path::Tiny
      - name: Install Dependency - File::Slurper
        shell: bash
        run: cpan File::Slurper
      - name: perl -V
        shell: bash
        run: perl -V
      - name: make test
        shell: bash
        run: make test
