name: Linux

on: [pull_request, push]

jobs:
  perl:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ["5.30"]

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: List Directory
        run: ls -l
      - name: Which CPAN
        shell: bash
        run: which cpan
      - name: perl -V
        shell: bash
        run: perl -V
      - name: make test
        shell: bash
        run: make test
