name: Linux

on: 
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - latest
          - threaded

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: ./build/depsinst.pl
      - name: Run Tests
        run: make test
